version: '3.8'

services:
  ffc-sfi-processing:
    build:
      context: .
      target: production
    image: ffc-sfi-processing
    container_name: ffc-sfi-processing
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfi-processing-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
