version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfi-processing:
    build:
      target: development
    image: ffc-sfi-processing-development
    container_name: ffc-sfi-processing-development
    ports:
      - "3010:3010"
      - "9240:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
